Hello
ElShaer398/Hello-Microverse pull request #1
Opened 2023-02-16 18:04 UTC by ElShaer398

Hello Microverse project.

2023-02-16 18:26 UTC, Zuhaib042 requested changes
Hi @ElShaer398 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
![close](https://media.giphy.com/media/z3piokwf0WPH81MOhu/giphy.gif)

## Highlights
✅ Correct Github flow

## Required Changes ♻️
- [ ] Kindly consider adding a Descriptive title to your pull request that tells what changes are inside and also consider adding a summary under the title with bullet points preferably describing what changes are in your pull request in detail.
- [ ] Kindly consider adding meaningful commit messages in Imperative tense. for example instead of writing `added .gitignore and linters` or `fixed linters errors`, you can write `Add .gitignore and linters to my project` or `Fix linters errors`.
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-16 18:26 UTC, Zuhaib042 commented on README.md
> +> Describe your project in 1 or 2 sentences.
- [ ] kindly consider removing this text and all the similar text like this in your readme because these guidelines text is referred to the author of this repo which is you to follow these guidelines and add relevant information about your project. leaving this kind of text makes it less professional.

2023-02-16 18:26 UTC, Zuhaib042 commented on README.md
> +> Describe the tech stack and include only the relevant sections that apply to your project.
- [ ] kindly remove  this for the reasons mentioned above.

2023-02-16 18:26 UTC, Zuhaib042 commented on README.md
> +</details>
- [ ] kindly consider removing these and adding only HTML and CSS in Client sub-section because this project dont have database or server.

2023-02-16 18:26 UTC, Zuhaib042 commented on README.md
> +
- [ ] kindly consider adding features for your project here for the reasons mentioned above.

2023-02-16 18:26 UTC, Zuhaib042 commented on README.md
> +- [Live Demo Link](https://yourdeployedapplicationlink.com)
- [ ] Kindly consider removing it as you don't have a demo link.

2023-02-16 18:26 UTC, Zuhaib042 commented on README.md
> +
- [ ] kindly consider filling this getting started section with relevant and appropriate information and write `not applicable` on any sub-section which is not relevant to your project.

2023-02-16 18:26 UTC, Zuhaib042 commented on README.md
> +- LinkedIn: [LinkedIn](https://linkedin.com/in/linkedinhandle)
- [ ] kindly consider adding your appropriate professional accounts links here so that the visitor can contact you.

2023-02-16 18:26 UTC, Zuhaib042 commented on README.md
> +- LinkedIn: [LinkedIn](https://linkedin.com/in/linkedinhandle)
- [ ] consider removing it as there is no second author.

2023-02-16 18:26 UTC, Zuhaib042 commented on README.md
> +- [ ] **[new_feature_3]**
- [ ] consider adding future features here.

2023-02-16 18:26 UTC, Zuhaib042 commented on README.md
> +
- [ ] You can remove this section if you want instead of leaving it like this here which is against professional repo standards.

2023-02-16 18:26 UTC, Zuhaib042 commented on .gitignore
> +node_modules
- [ ] Kindly consider adding `test.md` here as it is a project requirement.

2023-02-17 17:41 UTC, divinecharlotte requested changes
Hi @ElShaer398  , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## To Highlight 💯 
- No linters errors ✔️ 

## Required Changes ♻️

- [ ] I can see you did a good job by putting into action some of the requested changes but still some are missing kindly consider implementing the below-requested changes by the previous reviewer
![kin](https://user-images.githubusercontent.com/60146030/219720615-be12d70b-5281-4094-a753-aa981c888346.PNG)

- kindly make sure to add all the addressed changes  before submitting for another review this will save your time 

_Check the comments under the review._

![](https://media.giphy.com/media/tKyrc0NTlEcGWdThp4/giphy.gif)

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-17 17:41 UTC, divinecharlotte commented on README.md
> +
- [ ] please considers adding a meaningful description to your project on this part to make your readme more professional

2023-02-17 17:41 UTC, divinecharlotte commented on README.md
> +<!-- Features -->
- [ ] kindly consider adding tech stacks used in this project for example :`HTML and CSS` as its an HTML and CSS project

2023-02-17 17:41 UTC, divinecharlotte commented on .gitignore
> +node_modules
- [ ] kindly consider putting into consideration the above-requested changes

2023-02-18 18:37 UTC, didierganthier requested changes
Hi @ElShaer398  ,

🎉 Great job on addressing the feedback from the previous review! You've made some solid progress in implementing the requested changes. However, there are still a few areas that need some attention before we can move on to the next project.

<img src="https://media.giphy.com/media/L422JoNlBBBD42zkQ9/giphy.gif" />

## Highlights
- Descriptive PR ✔️ 
- Linters passing ✔️ 

## Required Changes 🛠
- Please review the comments under the review for specific changes that still need to be made.

## Optional Suggestions 💡
- [ ] Branch should have a name of a feature or action (e.g. 'created_sidebar' or 'added_comments_section'), this is optional as it wasn't mentioned by the previous reviewer.

- While these comments with the [OPTIONAL] prefix won't prevent the approval of this pull request, I strongly recommend taking them into account as they can improve your code. Some of them were missed by the previous reviewer and addressing them will really enhance your application.

🚀 Keep pushing forward, you're almost there! If you have any questions or need clarification on anything, feel free to leave a comment in the pull request thread and don't forget to tag me so I'll receive the notification.

**Please note**
- To avoid confusion and delays, please do not open a new pull request for re-reviews. Use the same pull request submitted for the first review, unless otherwise instructed.

------
As per the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561), you have a limited number of reviews per project. If you feel that the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s). 

Cheers and happy coding! 👏👏👏

2023-02-18 18:37 UTC, didierganthier commented on .gitignore
> +node_modules
Good job so far but this project requirement is still lacking 👆🏽

2023-02-18 18:37 UTC, didierganthier commented on README.md
> +<!-- Features -->
Add the `Tech Stacks` section as requested previously. Follow the structure of the [template](https://github.com/microverseinc/readme-template/blob/master/README.md) 🙂

2023-02-18 18:37 UTC, didierganthier commented on README.md
> +This project is [MIT](./LICENSE) licensed.
Make sure to create a `LICENSE` file so that this link won't be broken, the instructions for the content it should have are below in line `143` 😉

2023-02-18 19:23 UTC, MaganaAsiati requested changes
# STATUS: Required Changes ♻️♻️♻️ 
## Hi @ , I'm @MaganaAsiati, your reviewer for this PR  :wave: 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![so-close-gif-4](https://user-images.githubusercontent.com/95297251/191952218-b7185270-c02b-4e4d-89af-eae77fcd8bea.gif)

## Highlights

- Descriptive README file  :heavy_check_mark:👨🏻‍💻
- Great work using the right GitHub Flow.:heavy_check_mark:
- No Linter errors :heavy_check_mark:

## Required Changes ♻️

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._
- [ ] [OPTIONAL] Please make sure to make your commit messages more descriptive in the future. :heavy_check_mark:👨🏻‍💻
- [ ] kindly  Add a meaningful description to your pull request in the future which gives more information about what you implement in this milestone :heavy_check_mark:👨🏻‍💻


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2023-02-18 19:23 UTC, MaganaAsiati commented on .gitignore
> +node_modules
- Kindly add the test.md file in the git ignore  as required by the previous reviewer as it is part also of the project requirement 👌🏻

2023-02-18 21:15 UTC, algerina approved these changes
Hi @ElShaer398 ,

Good job so far! 

May I highlight the following:

- The repo looks professional.:heavy_check_mark:
- Your project looks awesome:heavy_check_mark:

## STATUS: APPROVED :muscle::clap:

Congratulations! :tada:

Your project is complete!  It's time to merge it :shipit:

<img src="https://media4.giphy.com/media/LlYjGi9rErbLjyaMNr/giphy.gif"/>

 
 ## Optional suggestions

 - Please check the comment under the review.

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._
Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread and tag me @algerina if something is not 100% clear.

#### _**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**_
------------------------------------------------------------------------------------------------------------------------------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)
___
_If anything seems to be unclear to you, reach out and ask anything by commenting on this Pull Request and mention me as [Algerina](https://github.com/algerina), I will receive a notification and will respond._

[GitHub](https://github.com/algerina) | [LinkedIn](https://linkedin.com/in/amel-khiri) | [Twitter](https://twitter.com/AmelQahwadji)

_Reviewed by [Amel Khiri ](https://github.com/algerina)_

2023-02-18 22:50 UTC, merged